### ISSUE TITLE
Add Guice

### ISSUE THREAD

**Issue by apontini** [Polpetta/jkk#8]
We need to add Guice to the project to allow easy testing and other cool stuff.
Issue opened to keep track of the progress

**Comment by apontini** [comment]
Guice seems to not play too well with Kotlin at a syntax level, I'll try to tinker some more with it and then i might start evaluating alternatives like [Dagger](https://dagger.dev/) or [Koin](https://github.com/InsertKoinIO/koin)

**Comment by Polpetta** [comment]
The main point of having dependency injection is to achieve simpler object initialization but also to provider an easy way to test stuff, passing simulators and/or mocks to the classes to test.

If think the last point is important as the first one, because otherwise it will a nightmare without tests.

**Comment by apontini** [comment]
Guice and Mockito have been added
